---
abstract: "An extended interface to Cloudmade's Geo API (geocoding, routing, drawing tiles)"
author:
  - 'Dmytro Gorbunov <dmitro.gorbunov@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-Cloudmade
no_index:
  directory:
    - t
    - inc
requires:
  JSON: 2
  LWP: 5
version: 0.6
